const $=id=>document.getElementById(id);
function formatTime(value){const ticks=Math.max(0,Math.round(value*10)),h=Math.floor(ticks/36000),m=Math.floor(ticks%36000/600),s=(ticks%600/10).toFixed(1).padStart(4,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`;}
function segments(distance){const out=[];if(distance%400)out.push(distance%400);return out.concat(Array(Math.floor(distance/400)).fill(400));}
function calculate(distance,target,adjustments){let dist=0,total=0,next=1000;return segments(distance).map((length,index)=>{const duration=Math.max(.1,target/distance*length+adjustments[index]),marks=[];while(next<=dist+length){marks.push({distance:next,time:total+duration*(next-dist)/length});next+=1000;}dist+=length;total+=duration;if(dist===distance&&distance%1000)marks.push({distance,time:total});return {length,duration,total,marks};});}
let activeDistance=5000,activeTarget=1200,adjustments=segments(5000).map(()=>0);
function draw(){const data=calculate(activeDistance,activeTarget,adjustments),total=data.at(-1).total,delta=Math.round((total-activeTarget)*10)/10;$('goal').textContent=formatTime(activeTarget);$('lap').textContent=formatTime(activeTarget/activeDistance*400);$('pace').textContent=formatTime(activeTarget/activeDistance*1000);$('adjusted').textContent=formatTime(total);$('schedule').textContent=(activeDistance%400?`${activeDistance%400}m + `:'')+`400m × ${Math.floor(activeDistance/400)}`;$('rows').innerHTML=data.map((r,i)=>`<div class="row"><div>${r.length}</div><div>${formatTime(r.duration)}<span class="lap-pace">${formatTime(r.duration/r.length*1000)}<small>/km</small></span></div><div class="controls"><button type="button" data-index="${i}" data-step="-1" aria-label="${i+1}번째 랩 1초 빠르게">−</button><span>${adjustments[i]>0?'+':''}${adjustments[i]}</span><button type="button" data-index="${i}" data-step="1" aria-label="${i+1}번째 랩 1초 느리게">+</button></div><div><strong>${formatTime(r.total)}</strong></div><div>${r.marks.map(m=>`<span class="mark">${m.distance/1000}km<b>${formatTime(m.time)}</b></span>`).join('')}</div></div>`).join('');$('sum').textContent=`${delta>0?'+':''}${delta}초`;$('final').textContent=formatTime(total);$('difference').textContent=delta===0?'동일':`${Math.abs(delta)}초 ${delta<0?'빠름':'느림'}`;}
function build(){const t=Number($('hours').value)*3600+Number($('minutes').value)*60+Number($('seconds').value);$('error').hidden=t>0;if(t<=0)return;activeTarget=t;activeDistance=Number($('distance').value);adjustments=segments(activeDistance).map(()=>0);draw();}
$('form').addEventListener('submit',e=>{e.preventDefault();build();});$('rows').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.index),base=activeTarget/activeDistance*segments(activeDistance)[i];adjustments[i]=Math.max(Math.ceil(.1-base),-30,Math.min(30,adjustments[i]+Number(b.dataset.step)));draw();});$('reset').addEventListener('click',()=>{adjustments.fill(0);draw();});$('distance').addEventListener('change',()=>{const defaults={5000:1200,8000:1920,10000:2400,20000:4800,21100:5400,40000:10200,42195:10800},t=defaults[$('distance').value];$('hours').value=Math.floor(t/3600);$('minutes').value=Math.floor(t%3600/60);$('seconds').value=t%60;build();});draw();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
